name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nadhil7
          outputs: |
            dist/snake.svg

      - name: Push generated SVG to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # FIXED
          branch: output
          directory: dist                            # FIXED
          force: true
